-- ============================================================
-- LABORATORY ASSET MANAGEMENT SYSTEM
-- SUPABASE DATABASE SCHEMA
-- ============================================================

create extension if not exists pgcrypto;

-- ============================================================
-- DROP EXISTING TABLES
-- ============================================================
-- Remove these statements when applying to a database
-- that already contains data.

drop table if exists public.audit_logs cascade;
drop table if exists public.maintenance_requests cascade;
drop table if exists public.borrowing_requests cascade;
drop table if exists public.equipment cascade;
drop table if exists public.profiles cascade;


-- ============================================================
-- PROFILES
-- ============================================================

create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null,
    email text,
    role text not null default 'requester'
        check (role in (
            'administrator',
            'laboratory_staff',
            'requester'
        )),
    created_at timestamptz not null default now()
);


-- ============================================================
-- EQUIPMENT
-- ============================================================

create table public.equipment (
    id bigint generated by default as identity primary key,
    asset_code text not null unique,
    equipment_name text not null,
    category text,
    description text,
    status text not null default 'Available'
        check (status in (
            'Available',
            'Borrowed',
            'Maintenance',
            'Damaged'
        )),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- BORROWING REQUESTS
-- ============================================================

create table public.borrowing_requests (
    id bigint generated by default as identity primary key,
    equipment_id bigint not null
        references public.equipment(id)
        on delete restrict,

    requester_id uuid not null
        references public.profiles(id)
        on delete restrict,

    purpose text not null,
    request_date timestamptz not null default now(),
    expected_return_date date,

    approved_by uuid
        references public.profiles(id)
        on delete set null,

    approved_at timestamptz,
    released_at timestamptz,
    returned_at timestamptz,

    status text not null default 'Pending'
        check (status in (
            'Pending',
            'Approved',
            'Rejected',
            'Released',
            'Returned',
            'Overdue',
            'Closed'
        )),

    remarks text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- MAINTENANCE REQUESTS
-- ============================================================

create table public.maintenance_requests (
    id bigint generated by default as identity primary key,

    equipment_id bigint not null
        references public.equipment(id)
        on delete restrict,

    requested_by uuid not null
        references public.profiles(id)
        on delete restrict,

    problem_description text not null,

    maintenance_status text not null default 'Pending'
        check (maintenance_status in (
            'Pending',
            'In Progress',
            'Completed',
            'Cancelled'
        )),

    priority text not null default 'Normal'
        check (priority in (
            'Low',
            'Normal',
            'High',
            'Urgent'
        )),

    created_at timestamptz not null default now(),
    completed_at timestamptz
);


-- ============================================================
-- AUDIT LOGS
-- ============================================================

create table public.audit_logs (
    id bigint generated by default as identity primary key,

    user_id uuid
        references public.profiles(id)
        on delete set null,

    action text not null,
    module text not null,
    record_id bigint,
    description text,
    created_at timestamptz not null default now()
);


-- ============================================================
-- INDEXES
-- ============================================================

create index idx_equipment_status
on public.equipment(status);

create index idx_borrowing_status
on public.borrowing_requests(status);

create index idx_borrowing_requester
on public.borrowing_requests(requester_id);

create index idx_borrowing_equipment
on public.borrowing_requests(equipment_id);

create index idx_maintenance_status
on public.maintenance_requests(maintenance_status);

create index idx_audit_user
on public.audit_logs(user_id);

create index idx_audit_created
on public.audit_logs(created_at desc);


-- ============================================================
-- FUNCTION: GET MY ROLE
-- ============================================================

create or replace function public.get_my_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
    select role
    from public.profiles
    where id = auth.uid();
$$;


-- ============================================================
-- FUNCTION: IS ADMIN
-- ============================================================

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and role = 'administrator'
    );
$$;


-- ============================================================
-- FUNCTION: IS STAFF OR ADMIN
-- ============================================================

create or replace function public.is_staff_or_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and role in (
              'administrator',
              'laboratory_staff'
          )
    );
$$;


-- ============================================================
-- FUNCTION: SET UPDATED AT
-- ============================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;


-- ============================================================
-- FUNCTION: SET EQUIPMENT AVAILABLE AFTER MAINTENANCE
-- ============================================================

create or replace function public.set_equipment_available_after_maintenance()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin

    if new.maintenance_status = 'Completed'
       and old.maintenance_status is distinct from 'Completed'
    then

        update public.equipment
        set status = 'Available'
        where id = new.equipment_id;

    end if;

    return new;

end;
$$;


-- ============================================================
-- TRIGGER: EQUIPMENT UPDATED AT
-- ============================================================

drop trigger if exists equipment_set_updated_at
on public.equipment;

create trigger equipment_set_updated_at
before update
on public.equipment
for each row
execute function public.set_updated_at();


-- ============================================================
-- TRIGGER: BORROWING UPDATED AT
-- ============================================================

drop trigger if exists borrowing_set_updated_at
on public.borrowing_requests;

create trigger borrowing_set_updated_at
before update
on public.borrowing_requests
for each row
execute function public.set_updated_at();


-- ============================================================
-- TRIGGER: MAINTENANCE COMPLETED
-- ============================================================

drop trigger if exists maintenance_completed_set_equipment_available
on public.maintenance_requests;

create trigger maintenance_completed_set_equipment_available
after update of maintenance_status
on public.maintenance_requests
for each row
execute function public.set_equipment_available_after_maintenance();

-- Repair equipment linked to maintenance requests completed before the trigger existed.
update public.equipment as e
set status = 'Available'
where exists (
        select 1
        from public.maintenance_requests as m
        where m.equipment_id = e.id
            and m.maintenance_status = 'Completed'
);


-- ============================================================
-- FUNCTION: HANDLE NEW AUTH USER
-- ============================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin

    insert into public.profiles (
        id,
        full_name,
        email
    )
    values (
        new.id,
        coalesce(
            new.raw_user_meta_data ->> 'full_name',
            split_part(new.email, '@', 1)
        ),
        new.email
    );

    return new;

end;
$$;


-- ============================================================
-- TRIGGER: CREATE PROFILE AFTER AUTH SIGNUP
-- ============================================================

-- IMPORTANT:
-- Remove the old trigger first so this SQL can be
-- safely executed multiple times.

drop trigger if exists on_auth_user_created
on auth.users;

create trigger on_auth_user_created
after insert
on auth.users
for each row
execute function public.handle_new_user();


-- ============================================================
-- ENABLE ROW LEVEL SECURITY
-- ============================================================

alter table public.profiles enable row level security;
alter table public.equipment enable row level security;
alter table public.borrowing_requests enable row level security;
alter table public.maintenance_requests enable row level security;
alter table public.audit_logs enable row level security;


-- ============================================================
-- PROFILES POLICIES
-- ============================================================

drop policy if exists profiles_select_own_or_admin
on public.profiles;

create policy profiles_select_own_or_admin
on public.profiles
for select
to authenticated
using (
    id = auth.uid()
    or public.is_admin()
);


drop policy if exists profiles_insert_admin
on public.profiles;

create policy profiles_insert_admin
on public.profiles
for insert
to authenticated
with check (
    public.is_admin()
);


drop policy if exists profiles_update_admin
on public.profiles;

create policy profiles_update_admin
on public.profiles
for update
to authenticated
using (
    public.is_admin()
)
with check (
    public.is_admin()
);


drop policy if exists profiles_delete_admin
on public.profiles;

create policy profiles_delete_admin
on public.profiles
for delete
to authenticated
using (
    public.is_admin()
);


-- ============================================================
-- EQUIPMENT POLICIES
-- ============================================================

drop policy if exists equipment_select_authenticated
on public.equipment;

create policy equipment_select_authenticated
on public.equipment
for select
to authenticated
using (true);


drop policy if exists equipment_insert_admin
on public.equipment;

create policy equipment_insert_admin
on public.equipment
for insert
to authenticated
with check (
    public.is_admin()
);


drop policy if exists equipment_update_admin
on public.equipment;

create policy equipment_update_admin
on public.equipment
for update
to authenticated
using (
    public.is_admin()
)
with check (
    public.is_admin()
);


drop policy if exists equipment_update_staff_or_admin
on public.equipment;

create policy equipment_update_staff_or_admin
on public.equipment
for update
to authenticated
using (
    public.is_staff_or_admin()
)
with check (
    public.is_staff_or_admin()
);


drop policy if exists equipment_delete_admin
on public.equipment;

create policy equipment_delete_admin
on public.equipment
for delete
to authenticated
using (
    public.is_admin()
);


-- ============================================================
-- BORROWING REQUEST POLICIES
-- ============================================================

drop policy if exists borrowing_select_own_or_staff
on public.borrowing_requests;

create policy borrowing_select_own_or_staff
on public.borrowing_requests
for select
to authenticated
using (
    requester_id = auth.uid()
    or public.is_staff_or_admin()
);


drop policy if exists borrowing_insert_own
on public.borrowing_requests;

create policy borrowing_insert_own
on public.borrowing_requests
for insert
to authenticated
with check (
    requester_id = auth.uid()
);


drop policy if exists borrowing_update_authorized
on public.borrowing_requests;

create policy borrowing_update_authorized
on public.borrowing_requests
for update
to authenticated
using (
    public.is_admin()
    or public.is_staff_or_admin()
    or (
        requester_id = auth.uid()
        and status = 'Pending'
    )
)
with check (
    public.is_admin()
    or public.is_staff_or_admin()
    or (
        requester_id = auth.uid()
        and status = 'Pending'
    )
);


drop policy if exists borrowing_delete_admin
on public.borrowing_requests;

create policy borrowing_delete_admin
on public.borrowing_requests
for delete
to authenticated
using (
    public.is_admin()
);


-- ============================================================
-- MAINTENANCE REQUEST POLICIES
-- ============================================================

drop policy if exists maintenance_select_own_or_staff
on public.maintenance_requests;

create policy maintenance_select_own_or_staff
on public.maintenance_requests
for select
to authenticated
using (
    requested_by = auth.uid()
    or public.is_staff_or_admin()
);


drop policy if exists maintenance_insert_staff
on public.maintenance_requests;

create policy maintenance_insert_staff
on public.maintenance_requests
for insert
to authenticated
with check (
    requested_by = auth.uid()
);


drop policy if exists maintenance_update_authorized
on public.maintenance_requests;

create policy maintenance_update_authorized
on public.maintenance_requests
for update
to authenticated
using (
    public.is_staff_or_admin()
)
with check (
    public.is_staff_or_admin()
);


drop policy if exists maintenance_delete_admin
on public.maintenance_requests;

create policy maintenance_delete_admin
on public.maintenance_requests
for delete
to authenticated
using (
    public.is_admin()
);


-- ============================================================
-- AUDIT LOG POLICIES
-- ============================================================

drop policy if exists audit_select_admin
on public.audit_logs;

create policy audit_select_admin
on public.audit_logs
for select
to authenticated
using (
    public.is_admin()
);


drop policy if exists audit_insert_own
on public.audit_logs;

create policy audit_insert_own
on public.audit_logs
for insert
to authenticated
with check (
    user_id = auth.uid()
);


drop policy if exists audit_delete_admin
on public.audit_logs;

create policy audit_delete_admin
on public.audit_logs
for delete
to authenticated
using (
    public.is_admin()
);


-- ============================================================
-- SAMPLE EQUIPMENT
-- ============================================================

insert into public.equipment (
    asset_code,
    equipment_name,
    category,
    description,
    status
)
values
(
    'LAP-001',
    'Laptop Computer',
    'Computer',
    'Laboratory laptop for academic activities',
    'Available'
),
(
    'LAP-002',
    'Laptop Computer',
    'Computer',
    'Laboratory laptop for academic activities',
    'Available'
),
(
    'LAP-003',
    'Laptop Computer',
    'Computer',
    'Laboratory laptop for academic activities',
    'Available'
),
(
    'PRJ-001',
    'Projector',
    'Presentation',
    'LCD projector for classroom presentation',
    'Available'
),
(
    'PRJ-002',
    'Projector',
    'Presentation',
    'LCD projector for classroom presentation',
    'Available'
),
(
    'CAM-001',
    'Digital Camera',
    'Multimedia',
    'Digital camera for laboratory documentation',
    'Available'
),
(
    'MIC-001',
    'Wireless Microphone',
    'Audio',
    'Wireless microphone set',
    'Available'
),
(
    'MON-001',
    'Computer Monitor',
    'Computer',
    '24 inch laboratory monitor',
    'Available'
);